BEGIN;

-- =====================================
-- BD POR EMPRESA (operativa)
-- =====================================

-- Proyectos
CREATE TABLE IF NOT EXISTS tb_proyectos (
  p_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  p_nombre        VARCHAR(45) NOT NULL,
  p_descripcion   VARCHAR(250),
  p_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  p_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  p_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  p_modificado_en TIMESTAMPTZ,
  p_borrado_en    TIMESTAMPTZ
);

-- Nodos
CREATE TABLE IF NOT EXISTS tb_nodos (
  n_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  n_nombre        VARCHAR(45) NOT NULL,
  n_ubicacion     VARCHAR(100),
  n_id_proyecto   INT REFERENCES tb_proyectos(p_id)
                     ON UPDATE CASCADE ON DELETE SET NULL,
  n_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  n_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  n_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  n_modificado_en TIMESTAMPTZ,
  n_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_nodos_proyecto ON tb_nodos(n_id_proyecto);

-- Sensores
CREATE TABLE IF NOT EXISTS tb_sensores (
  s_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s_nombre        VARCHAR(45) NOT NULL,
  s_id_nodo       INT NOT NULL REFERENCES tb_nodos(n_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
  s_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  s_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  s_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  s_modificado_en TIMESTAMPTZ,
  s_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sensores_nodo ON tb_sensores(s_id_nodo);

-- Catálogo: tipos de dato de sensores
CREATE TABLE IF NOT EXISTS tb_sensores_tipos_dato (
  std_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  std_nombre        VARCHAR(100) NOT NULL,
  std_unidad        VARCHAR(15),
  std_descripcion   VARCHAR(250),
  std_var_json      VARCHAR(15),  -- nombre de la variable en el JSON recibido
  std_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  std_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  std_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  std_modificado_en TIMESTAMPTZ,
  std_borrado_en    TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_std_nombre ON tb_sensores_tipos_dato (LOWER(std_nombre));

-- M:N Sensores ↔ Tipos soportados
CREATE TABLE IF NOT EXISTS tb_tipos_sensores_soportados (
  tss_id_sensor INT NOT NULL REFERENCES tb_sensores(s_id)
                  ON UPDATE CASCADE ON DELETE CASCADE,
  tss_id_tipo   INT NOT NULL REFERENCES tb_sensores_tipos_dato(std_id)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
  tss_estado       BOOLEAN NOT NULL DEFAULT TRUE,
  tss_borrado      BOOLEAN NOT NULL DEFAULT FALSE,
  tss_creado_en    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tss_modificado_en TIMESTAMPTZ,
  tss_borrado_en    TIMESTAMPTZ,
  CONSTRAINT pk_tss PRIMARY KEY (tss_id_sensor, tss_id_tipo)
);
CREATE INDEX IF NOT EXISTS idx_tss_tipo ON tb_tipos_sensores_soportados(tss_id_tipo);

-- Lecturas
CREATE TABLE IF NOT EXISTS tb_lecturas_sensores (
  ls_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ls_valor            DOUBLE PRECISION NOT NULL,
  ls_fecha            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ls_id_sensor        INT NOT NULL REFERENCES tb_sensores(s_id)
                         ON UPDATE CASCADE ON DELETE RESTRICT,
  ls_id_sensores_tipo INT NOT NULL REFERENCES tb_sensores_tipos_dato(std_id)
                         ON UPDATE CASCADE ON DELETE RESTRICT,
  ls_estado           BOOLEAN NOT NULL DEFAULT TRUE,
  ls_borrado          BOOLEAN NOT NULL DEFAULT FALSE,
  ls_creado_en        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ls_modificado_en    TIMESTAMPTZ,
  ls_borrado_en       TIMESTAMPTZ,
  CONSTRAINT fk_ls_sensor_tipo_soportado
    FOREIGN KEY (ls_id_sensor, ls_id_sensores_tipo)
    REFERENCES tb_tipos_sensores_soportados(tss_id_sensor, tss_id_tipo)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_ls_sensor_fecha ON tb_lecturas_sensores(ls_id_sensor, ls_fecha);
CREATE INDEX IF NOT EXISTS idx_ls_tipo_fecha   ON tb_lecturas_sensores(ls_id_sensores_tipo, ls_fecha);

-- Umbrales
CREATE TABLE IF NOT EXISTS tb_umbrales (
  um_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  um_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
  um_id_tipo       INT NOT NULL REFERENCES tb_sensores_tipos_dato(std_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
  um_valor_min     DOUBLE PRECISION,
  um_valor_max     DOUBLE PRECISION,
  um_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  um_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  um_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  um_modificado_en TIMESTAMPTZ,
  um_borrado_en    TIMESTAMPTZ,
  CONSTRAINT uq_umbral_sensor_tipo UNIQUE (um_id_sensor, um_id_tipo),
  CONSTRAINT ck_umbral_rango CHECK (
    (um_valor_min IS NULL OR um_valor_max IS NULL) OR (um_valor_min <= um_valor_max)
  )
);
CREATE INDEX IF NOT EXISTS idx_um_sensor_tipo ON tb_umbrales(um_id_sensor, um_id_tipo);

-- Alertas
CREATE TABLE IF NOT EXISTS tb_alertas (
  a_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a_mensaje       VARCHAR(100) NOT NULL,
  a_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
  a_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  a_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  a_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  a_modificado_en TIMESTAMPTZ,
  a_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alertas_sensor_fecha ON tb_alertas(a_id_sensor, a_creado_en);

-- Distribución de alertas a usuarios (IDs de usuario global)
CREATE TABLE IF NOT EXISTS tb_alertas_usuarios (
  au_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  au_id_alerta     INT NOT NULL REFERENCES tb_alertas(a_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
  au_id_usuario    INT NOT NULL, -- ID del usuario global (no FK cross-DB)
  au_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  au_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  au_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  au_leido         BOOLEAN NOT NULL DEFAULT FALSE,
  au_leido_en      TIMESTAMPTZ,
  au_modificado_en TIMESTAMPTZ,
  au_borrado_en    TIMESTAMPTZ,
  CONSTRAINT uq_alerta_usuario UNIQUE (au_id_alerta, au_id_usuario)
);
CREATE INDEX IF NOT EXISTS idx_au_usuario ON tb_alertas_usuarios(au_id_usuario);
CREATE INDEX IF NOT EXISTS idx_au_alerta  ON tb_alertas_usuarios(au_id_alerta);

COMMIT;
