BEGIN;

-- ============================================
--   1) PROYECTOS
-- ============================================
CREATE TABLE IF NOT EXISTS tb_proyectos (
  p_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  p_nombre        VARCHAR(45) NOT NULL,
  p_descripcion   VARCHAR(250),
  p_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  p_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  p_modificado_en TIMESTAMPTZ,
  p_borrado_en    TIMESTAMPTZ
);

-- ============================================
--   2) NODOS
-- ============================================
CREATE TABLE IF NOT EXISTS tb_nodos (
  n_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  n_nombre        VARCHAR(45) NOT NULL,
  n_ubicacion     VARCHAR(100),
  n_id_proyecto   INT REFERENCES tb_proyectos(p_id)
                     ON UPDATE CASCADE ON DELETE SET NULL,
  n_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  n_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  n_modificado_en TIMESTAMPTZ,
  n_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_nodos_proyecto ON tb_nodos(n_id_proyecto);

-- ============================================
--   3) SENSORES
-- ============================================
CREATE TABLE IF NOT EXISTS tb_sensores (
  s_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s_nombre        VARCHAR(45) NOT NULL,
  s_id_nodo       INT NOT NULL REFERENCES tb_nodos(n_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
  s_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  s_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  s_modificado_en TIMESTAMPTZ,
  s_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sensores_nodo ON tb_sensores(s_id_nodo);

-- ============================================
--   4) VARIABLES (Catálogo global)
-- ============================================
CREATE TABLE IF NOT EXISTS tb_variables (
  v_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  v_nombre        VARCHAR(100) NOT NULL,
  v_unidad        VARCHAR(15),
  v_descripcion   VARCHAR(250),
  v_var_json      VARCHAR(15) NOT NULL UNIQUE,
  v_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  v_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  v_modificado_en TIMESTAMPTZ,
  v_borrado_en    TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_variables_nombre ON tb_variables (LOWER(v_nombre));

-- ============================================
--   5) SENSORES ↔ VARIABLES  (M:N)
-- ============================================
CREATE TABLE IF NOT EXISTS tb_variables_soporta_sensores (
  vss_id            SERIAL PRIMARY KEY,      -- << NUEVA PK >>
  
  vss_id_sensor     INT NOT NULL,
  vss_id_variable   INT NOT NULL,

  vss_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  vss_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  vss_modificado_en TIMESTAMPTZ,
  vss_borrado_en    TIMESTAMPTZ,

  CONSTRAINT fk_vss_sensor   FOREIGN KEY (vss_id_sensor)
      REFERENCES tb_sensores(s_id)
      ON UPDATE CASCADE
      ON DELETE CASCADE,

  CONSTRAINT fk_vss_variable FOREIGN KEY (vss_id_variable)
      REFERENCES tb_variables(v_id)
      ON UPDATE CASCADE
      ON DELETE RESTRICT,

  -- Evita duplicados lógicos
  CONSTRAINT uq_vss UNIQUE (vss_id_sensor, vss_id_variable)
);

CREATE INDEX IF NOT EXISTS idx_vss_variable
  ON tb_variables_soporta_sensores(vss_id_variable);

-- ============================================
--   6) LECTURAS DE SENSORES
-- ============================================
CREATE TABLE IF NOT EXISTS tb_lecturas_sensores (
  ls_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ls_valor         DOUBLE PRECISION NOT NULL,
  ls_fecha         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ls_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
  ls_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
  ls_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  ls_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ls_modificado_en TIMESTAMPTZ,
  ls_borrado_en    TIMESTAMPTZ,

  -- Verificar que la lectura pertenece a una variable soportada
  CONSTRAINT fk_ls_sensor_variable
    FOREIGN KEY (ls_id_sensor, ls_id_variable)
    REFERENCES tb_variables_soporta_sensores(vss_id_sensor, vss_id_variable)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_ls_sensor_fecha 
    ON tb_lecturas_sensores(ls_id_sensor, ls_fecha);

CREATE INDEX IF NOT EXISTS idx_ls_variable_fecha 
    ON tb_lecturas_sensores(ls_id_variable, ls_fecha);

-- ============================================
--   7) UMBRALES
-- ============================================
CREATE TABLE IF NOT EXISTS tb_umbrales (
  um_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  um_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
  um_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
  um_valor_min     DOUBLE PRECISION,
  um_valor_max     DOUBLE PRECISION,
  um_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  um_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  um_modificado_en TIMESTAMPTZ,
  um_borrado_en    TIMESTAMPTZ,

  CONSTRAINT uq_umbral UNIQUE (um_id_sensor, um_id_variable),

  CONSTRAINT ck_umbral_rango CHECK (
    (um_valor_min IS NULL OR um_valor_max IS NULL)
    OR (um_valor_min <= um_valor_max)
  )
);
CREATE INDEX IF NOT EXISTS idx_um_sensor_variable ON tb_umbrales(um_id_sensor, um_id_variable);

-- ============================================
--   8) ALERTAS
-- ============================================
CREATE TABLE IF NOT EXISTS tb_alertas (
  a_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a_mensaje       VARCHAR(100) NOT NULL,
  a_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
  a_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  a_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  a_modificado_en TIMESTAMPTZ,
  a_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alertas_sensor_fecha 
    ON tb_alertas(a_id_sensor, a_creado_en);

-- ============================================
--   9) ALERTAS → USUARIOS
-- ============================================
CREATE TABLE IF NOT EXISTS tb_alertas_usuarios (
  au_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  au_id_alerta     INT NOT NULL REFERENCES tb_alertas(a_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
  au_id_usuario    INT NOT NULL,
  au_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  au_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  au_leido         BOOLEAN NOT NULL DEFAULT FALSE,
  au_leido_en      TIMESTAMPTZ,
  au_modificado_en TIMESTAMPTZ,
  au_borrado_en    TIMESTAMPTZ,

  CONSTRAINT uq_alerta_usuario UNIQUE (au_id_alerta, au_id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_au_usuario ON tb_alertas_usuarios(au_id_usuario);
CREATE INDEX IF NOT EXISTS idx_au_alerta  ON tb_alertas_usuarios(au_id_alerta);

COMMIT;
