BEGIN;

-- =========================
-- BD GENERAL (6 TABLAS)
-- =========================

-- 1) EMPRESAS (tenants)
CREATE TABLE IF NOT EXISTS tb_empresas (
  e_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  e_nombre        VARCHAR(45) NOT NULL,
  e_descripcion   VARCHAR(250),
  e_email         VARCHAR(100),
  e_numero_tel    VARCHAR(20),
  e_responsable   VARCHAR(100),
  e_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  e_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  e_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  e_modificado_en TIMESTAMPTZ,
  e_borrado_en    TIMESTAMPTZ
);

-- 2) CONEXIONES a la BD de cada empresa
CREATE TABLE IF NOT EXISTS tb_conexiones (
  c_id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  c_id_empresa         INT NOT NULL REFERENCES tb_empresas(e_id)
                          ON UPDATE CASCADE ON DELETE CASCADE,
  c_host               VARCHAR(100),   -- opcional si usas otro host
  c_puerto             INT,            -- opcional
  c_nombre_base_de_datos VARCHAR(45) NOT NULL,
  c_usuario            VARCHAR(45) NOT NULL,
  c_contrasena         VARCHAR(255) NOT NULL,
  c_estado             BOOLEAN NOT NULL DEFAULT TRUE,
  c_borrado            BOOLEAN NOT NULL DEFAULT FALSE,
  c_creado_en          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  c_modificado_en      TIMESTAMPTZ,
  c_borrado_en         TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_conexiones_empresa ON tb_conexiones(c_id_empresa);

-- 3) ROLES globales
CREATE TABLE IF NOT EXISTS tb_roles_usuarios (
  ru_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ru_nombre        VARCHAR(45) NOT NULL UNIQUE,
  ru_descripcion   VARCHAR(250),
  ru_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  ru_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  ru_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ru_modificado_en TIMESTAMPTZ,
  ru_borrado_en    TIMESTAMPTZ
);

-- 4) USUARIOS globales
CREATE TABLE IF NOT EXISTS tb_usuarios (
  u_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  u_nombre        VARCHAR(45) NOT NULL,
  u_email         VARCHAR(100) NOT NULL UNIQUE,
  u_contrasena    VARCHAR(255) NOT NULL,
  u_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  u_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  u_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  u_modificado_en TIMESTAMPTZ,
  u_borrado_en    TIMESTAMPTZ
);

-- 5) PERFILES (usuario-rol-empresa)
CREATE TABLE IF NOT EXISTS tb_perfiles (
  p_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  p_id_usuario    INT NOT NULL REFERENCES tb_usuarios(u_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
  p_id_rol        INT NOT NULL REFERENCES tb_roles_usuarios(ru_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
  p_id_empresa    INT NOT NULL REFERENCES tb_empresas(e_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
  p_estado        BOOLEAN NOT NULL DEFAULT TRUE,
  p_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
  p_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  p_modificado_en TIMESTAMPTZ,
  p_borrado_en    TIMESTAMPTZ,
  CONSTRAINT uq_perfil UNIQUE (p_id_usuario, p_id_rol, p_id_empresa)
);
CREATE INDEX IF NOT EXISTS idx_perfiles_usuario ON tb_perfiles(p_id_usuario);
CREATE INDEX IF NOT EXISTS idx_perfiles_empresa ON tb_perfiles(p_id_empresa);

-- 6) DATOS CRUDOS globales (staging)
CREATE TABLE IF NOT EXISTS tb_datos_crudos (
  dc_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dc_id_empresa   INT REFERENCES tb_empresas(e_id)
                     ON UPDATE CASCADE ON DELETE SET NULL,
  dc_id_nodo      BIGINT,             -- puede ser NULL (sin FK cross-DB)
  dc_mensaje      JSON NOT NULL,
  dc_recibido_en  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  dc_error_log    TEXT,
  dc_estado       BOOLEAN NOT NULL DEFAULT TRUE,
  dc_borrado      BOOLEAN NOT NULL DEFAULT FALSE,
  dc_modificado_en TIMESTAMPTZ,
  dc_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_dc_empresa  ON tb_datos_crudos(dc_id_empresa);
CREATE INDEX IF NOT EXISTS idx_dc_recibido ON tb_datos_crudos(dc_recibido_en);
CREATE INDEX IF NOT EXISTS idx_dc_nodo     ON tb_datos_crudos(dc_id_nodo);

COMMIT;

