-- ========================= --
-- CREACION DE PRIMERA BASE DE DATOS DE EMPRESA(Tech Solutions)
-- ========================= --

CREATE DATABASE iot_tech_solutions_db;

\c iot_tech_solutions_db;

-- =========================
--  EMPRESARIAL (TENANT)
-- =========================

-- PROYECTOS
CREATE TABLE IF NOT EXISTS tb_proyectos (
	p_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	p_nombre         VARCHAR(45) NOT NULL,
	p_descripcion    VARCHAR(250),
	p_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	p_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	p_modificado_en  TIMESTAMPTZ,
	p_borrado_en     TIMESTAMPTZ
);

-- NODOS
CREATE TABLE IF NOT EXISTS tb_nodos (
	n_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	n_nombre         VARCHAR(45) NOT NULL,
	n_ubicacion      VARCHAR(100),
	n_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	n_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	n_modificado_en  TIMESTAMPTZ,
	n_borrado_en     TIMESTAMPTZ,
	n_id_proyecto    INT NOT NULL REFERENCES tb_proyectos(p_id)
											ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nodos_proyecto ON tb_nodos(n_id_proyecto);

-- SENSORES
CREATE TABLE IF NOT EXISTS tb_sensores (
	s_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	s_nombre         VARCHAR(45) NOT NULL,
	s_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	s_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	s_modificado_en  TIMESTAMPTZ,
	s_borrado_en     TIMESTAMPTZ,
	s_id_nodo        INT NOT NULL REFERENCES tb_nodos(n_id)
											ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sensores_nodo ON tb_sensores(s_id_nodo);

-- VARIABLES (catálogo)
CREATE TABLE IF NOT EXISTS tb_variables (
	v_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	v_nombre         VARCHAR(100) NOT NULL,
	v_unidad         VARCHAR(15),
	v_descripcion    VARCHAR(250),
	v_var_json       VARCHAR(100) NOT NULL UNIQUE,
	v_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	v_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	v_modificado_en  TIMESTAMPTZ,
	v_borrado_en     TIMESTAMPTZ
);

-- M:N SENSOR ↔ VARIABLE
CREATE TABLE IF NOT EXISTS tb_variables_soporta_sensores (
	vss_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vss_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
												ON UPDATE CASCADE ON DELETE CASCADE,
	vss_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
												ON UPDATE CASCADE ON DELETE RESTRICT,
	vss_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	vss_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	vss_modificado_en TIMESTAMPTZ,
	vss_borrado_en    TIMESTAMPTZ
);

-- inserto proyecto de prueba
INSERT INTO tb_proyectos (p_nombre, p_descripcion)
VALUES
('Proyecto Tech', 'Proyecto de monitoreo para Tech Solutions');

-- inserto 2 nodos de prueba en el proyecto
INSERT INTO tb_nodos (n_nombre, n_ubicacion, n_id_proyecto)
VALUES ('Nodo 1', 'Centro de Datos', 1),
('Nodo 2', 'Oficinas', 1);

-- inserto sensores de prueba
INSERT INTO tb_sensores (s_nombre, s_id_nodo)
VALUES
('SENSOR_01 - Ambiental', 1),
('SENSOR_02 - Energía', 1),
('SENSOR_03 - Temperatura', 2),
('SENSOR_04 - Potencia', 2);

INSERT INTO tb_variables (v_nombre, v_unidad, v_descripcion, v_var_json)
VALUES
('Temperatura', '°C', 'Temperatura ambiente o técnica', 'temperatura'),
('Humedad', '%', 'Humedad relativa del aire', 'humedad'),
('Luminosidad', 'lux', 'Nivel de iluminación', 'luminosidad'),
('Voltaje', 'V', 'Voltaje eléctrico', 'voltaje'),
('Potencia', 'W', 'Potencia eléctrica activa', 'potencia');

-- Sensor 1
INSERT INTO tb_variables_soporta_sensores (vss_id_sensor, vss_id_variable)
SELECT 1, v_id FROM tb_variables
WHERE v_var_json IN ('luminosidad', 'voltaje');

-- Sensor 2
INSERT INTO tb_variables_soporta_sensores (vss_id_sensor, vss_id_variable)
SELECT 2, v_id FROM tb_variables
WHERE v_var_json IN ('humedad', 'potencia');

-- Sensor 3
INSERT INTO tb_variables_soporta_sensores (vss_id_sensor, vss_id_variable)
SELECT 3, v_id FROM tb_variables
WHERE v_var_json IN ('temperatura', 'humedad');

-- Sensor 4
INSERT INTO tb_variables_soporta_sensores (vss_id_sensor, vss_id_variable)
SELECT 4, v_id FROM tb_variables
WHERE v_var_json = 'potencia';


-- UMBRALES
CREATE TABLE IF NOT EXISTS tb_umbrales (
	um_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	um_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	um_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	um_valor_min     DOUBLE PRECISION,
	um_valor_max     DOUBLE PRECISION,
	um_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	um_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	um_modificado_en TIMESTAMPTZ,
	um_borrado_en    TIMESTAMPTZ,
	CONSTRAINT uq_umbral UNIQUE (um_id_sensor, um_id_variable),
	CONSTRAINT ck_umbral_rango CHECK (
		(um_valor_min IS NULL OR um_valor_max IS NULL) OR (um_valor_min <= um_valor_max)
	),
	CONSTRAINT ck_umbral_not_both_null CHECK (
		(um_valor_min IS NOT NULL OR um_valor_max IS NOT NULL)
	)
);
CREATE INDEX IF NOT EXISTS idx_um_sensor_variable ON tb_umbrales(um_id_sensor, um_id_variable);

-- LECTURAS DE SENSORES
CREATE TABLE IF NOT EXISTS tb_lecturas_sensores (
	ls_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ls_valor         VARCHAR(255) NOT NULL,
	ls_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	ls_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	ls_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	ls_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ls_modificado_en TIMESTAMPTZ,
	ls_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_lecturas_sensor   ON tb_lecturas_sensores(ls_id_sensor);
CREATE INDEX IF NOT EXISTS idx_lecturas_variable ON tb_lecturas_sensores(ls_id_variable);
CREATE INDEX IF NOT EXISTS idx_lecturas_fecha    ON tb_lecturas_sensores(ls_creado_en);

-- ALERTAS
CREATE TABLE IF NOT EXISTS tb_alertas (
	a_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	a_mensaje       VARCHAR(250) NOT NULL,
	a_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
										 ON UPDATE CASCADE ON DELETE RESTRICT,
	a_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	a_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	a_modificado_en TIMESTAMPTZ,
	a_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alertas_sensor_fecha ON tb_alertas(a_id_sensor, a_creado_en);

-- ALERTAS POR USUARIO
CREATE TABLE IF NOT EXISTS tb_alertas_usuarios (
	au_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	au_id_alerta     INT NOT NULL REFERENCES tb_alertas(a_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	au_id_usuario    INT NOT NULL,
	au_leido         BOOLEAN NOT NULL DEFAULT FALSE,
	au_leido_en      TIMESTAMPTZ,
	au_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	au_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
	au_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	au_modificado_en TIMESTAMPTZ,
	au_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_au_usuario ON tb_alertas_usuarios(au_id_usuario);