-- =========================
--  NUCLEO / MULTI-TENANT
-- =========================

-- EMPRESAS
CREATE TABLE IF NOT EXISTS tb_empresas (
	e_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	e_nombre         VARCHAR(45) NOT NULL,
	e_descripcion    VARCHAR(250),
	e_email          VARCHAR(100),
	e_numero_tel     VARCHAR(20),
	e_responsable    VARCHAR(100),
	e_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	e_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	e_modificado_en  TIMESTAMPTZ,
	e_borrado_en     TIMESTAMPTZ
);

-- Creo empresa "cero" para usuario admin
INSERT INTO tb_empresas (e_id, e_nombre, e_descripcion, e_email, e_numero_tel, e_responsable)
VALUES (0, 'Empresa Principal', 'Empresa principal del sistema', 'admin@empresa-principal.com', '+0000000000', 'Admin Principal');

-- Inserto datos de prueba
INSERT INTO tb_empresas (e_nombre, e_descripcion, e_email, e_numero_tel, e_responsable)
VALUES ('Empresa Demo', 'Empresa de demostración para pruebas', 'contacto@empresa-demo.com', '+1234567890', 'Juan Pérez'),
('Tech Solutions', 'Proveedor de soluciones tecnológicas', 'contacto@tech-solutions.com', '+1122334455', 'Carlos Martínez');

-- ROLES (globales)
CREATE TABLE IF NOT EXISTS tb_roles_usuarios (
	ru_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ru_nombre        VARCHAR(255) NOT NULL UNIQUE,
	ru_descripcion   TEXT,
	ru_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	ru_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ru_modificado_en TIMESTAMPTZ,
	ru_borrado_en    TIMESTAMPTZ
);

-- Inserto roles
INSERT INTO tb_roles_usuarios (ru_nombre, ru_descripcion)
VALUES ('ADMIN_GLOBAL', 'Administrador del sistema con todos los permisos'),
('ADMIN', 'Usuario con permisos limitados'); --ToDO: cambiar a usuario

-- USUARIOS (Auth / Usuario comparten la misma tabla)
CREATE TABLE IF NOT EXISTS tb_usuarios (
	u_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	u_nombre         VARCHAR(45) NOT NULL,
	u_apellido       VARCHAR(45),
	u_email          VARCHAR(100) NOT NULL UNIQUE,
	u_contrasena     VARCHAR(255) NOT NULL,
	u_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	u_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	u_modificado_en  TIMESTAMPTZ,
	u_borrado_en     TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_usuario_email ON tb_usuarios(u_email);

-- Inserto usuario admin
INSERT INTO tb_usuarios (u_nombre, u_apellido, u_email, u_contrasena)
VALUES ('Admin', 'Global', 'admin@global.com', '$2a$12$DFJL8KOzcl9Z5.dUjKQ/c.Rmut3RUJEKKBpN4XDOgc62xcDwBx0Xy'); --admin1234

--Inserto usuario normal de prueba(empresa 1)
INSERT INTO tb_usuarios (u_nombre, u_apellido, u_email, u_contrasena)
VALUES ('Usuario', 'Normal', 'usuario@empresa-demo.com', '$2a$12$gJguF9hjErSzK7/zs4CWPu4aXhbZX/mDeZWPChP2FCfu4QLOKy49u'); --user1234

--Inserto usuario normal de prueba(empresa 2)
INSERT INTO tb_usuarios (u_nombre, u_apellido, u_email, u_contrasena)
VALUES ('Carlos', 'Martínez', 'carlos@tech-solutions.com', '$2a$12$gJguF9hjErSzK7/zs4CWPu4aXhbZX/mDeZWPChP2FCfu4QLOKy49u'); --user1234

-- CONEXIONES A BD DE EMPRESA
CREATE TABLE IF NOT EXISTS tb_conexiones (
	c_id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	c_id_empresa           INT NOT NULL REFERENCES tb_empresas(e_id)
														ON UPDATE CASCADE ON DELETE CASCADE,
	c_host                 VARCHAR(100),
	c_puerto               INT,
	c_nombre_base_de_datos VARCHAR(45) NOT NULL,
	c_usuario              VARCHAR(45) NOT NULL,
	c_contrasena           VARCHAR(255) NOT NULL,
	c_estado               BOOLEAN NOT NULL DEFAULT TRUE,
	c_creado_en            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	c_modificado_en        TIMESTAMPTZ,
	c_borrado_en           TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_conexiones_empresa ON tb_conexiones(c_id_empresa);

-- Inserto datos de prueba para empresa demo
INSERT INTO tb_conexiones (c_id_empresa, c_host, c_puerto, c_nombre_base_de_datos, c_usuario, c_contrasena)
VALUES (1, 'localhost', 5434, 'iot_empresa_demo_db', 'postgres', 'Aragot123');

-- Inserto datos de prueba para empresa tech solutions
INSERT INTO tb_conexiones (c_id_empresa, c_host, c_puerto, c_nombre_base_de_datos, c_usuario, c_contrasena)
VALUES (2, 'localhost', 5434, 'iot_tech_solutions_db', 'postgres', 'Aragot123');

-- PERFILES (usuario-rol-empresa)
CREATE TABLE IF NOT EXISTS tb_perfiles (
	p_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	p_id_usuario     INT NOT NULL REFERENCES tb_usuarios(u_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	p_id_rol         INT NOT NULL REFERENCES tb_roles_usuarios(ru_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	p_id_empresa     INT NOT NULL REFERENCES tb_empresas(e_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	p_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	p_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	p_modificado_en  TIMESTAMPTZ,
	p_borrado_en     TIMESTAMPTZ,
	CONSTRAINT uq_perfil UNIQUE (p_id_usuario, p_id_rol, p_id_empresa)
);
CREATE INDEX IF NOT EXISTS idx_perfiles_usuario ON tb_perfiles(p_id_usuario);
CREATE INDEX IF NOT EXISTS idx_perfiles_empresa ON tb_perfiles(p_id_empresa);

--Inserto perfil admin para empresa demo
INSERT INTO tb_perfiles (p_id_usuario, p_id_rol, p_id_empresa)
VALUES (1, 1, 0); -- Admin Principal como Admin de Empresa Demo

--Inserto perfil usuario normal para empresa demo
INSERT INTO tb_perfiles (p_id_usuario, p_id_rol, p_id_empresa)
VALUES (2, 2, 1); -- Usuario Normal como Usuario de Empresa 1

--Inserto perfil usuario normal para empresa tech solutions
INSERT INTO tb_perfiles (p_id_usuario, p_id_rol, p_id_empresa)
VALUES (3, 2, 2); -- Carlos Martínez como Usuario de Empresa 2

-- DATOS CRUDOS (staging)
CREATE TABLE IF NOT EXISTS tb_datos_crudos (
	dc_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dc_id_empresa    INT REFERENCES tb_empresas(e_id)
											ON UPDATE CASCADE ON DELETE SET NULL,
	dc_id_nodo       BIGINT,
	dc_mensaje       JSONB NOT NULL,
	dc_recibido_en   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	dc_error_log     TEXT,
	dc_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	dc_modificado_en TIMESTAMPTZ,
	dc_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_dc_empresa  ON tb_datos_crudos(dc_id_empresa);
CREATE INDEX IF NOT EXISTS idx_dc_recibido ON tb_datos_crudos(dc_recibido_en);
CREATE INDEX IF NOT EXISTS idx_dc_nodo     ON tb_datos_crudos(dc_id_nodo);

-- ========================= --
-- CREACION DE PRIMERA BASE DE DATOS DE EMPRESA(DEMO)
-- ========================= --

CREATE DATABASE iot_empresa_demo_db;

\c iot_empresa_demo_db;

-- =========================
--  EMPRESARIAL (TENANT)
-- =========================

-- PROYECTOS
CREATE TABLE IF NOT EXISTS tb_proyectos (
	p_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	p_nombre         VARCHAR(45) NOT NULL,
	p_descripcion    VARCHAR(250),
	p_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	p_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	p_modificado_en  TIMESTAMPTZ,
	p_borrado_en     TIMESTAMPTZ
);

-- NODOS
CREATE TABLE IF NOT EXISTS tb_nodos (
	n_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	n_nombre         VARCHAR(45) NOT NULL,
	n_ubicacion      VARCHAR(100),
	n_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	n_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	n_modificado_en  TIMESTAMPTZ,
	n_borrado_en     TIMESTAMPTZ,
	n_id_proyecto    INT NOT NULL REFERENCES tb_proyectos(p_id)
											ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nodos_proyecto ON tb_nodos(n_id_proyecto);

-- SENSORES
CREATE TABLE IF NOT EXISTS tb_sensores (
	s_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	s_nombre         VARCHAR(45) NOT NULL,
	s_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	s_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	s_modificado_en  TIMESTAMPTZ,
	s_borrado_en     TIMESTAMPTZ,
	s_id_nodo        INT NOT NULL REFERENCES tb_nodos(n_id)
											ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sensores_nodo ON tb_sensores(s_id_nodo);

-- VARIABLES (catálogo)
CREATE TABLE IF NOT EXISTS tb_variables (
	v_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	v_nombre         VARCHAR(100) NOT NULL,
	v_unidad         VARCHAR(15),
	v_descripcion    VARCHAR(250),
	v_var_json       VARCHAR(100) NOT NULL UNIQUE,
	v_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	v_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	v_modificado_en  TIMESTAMPTZ,
	v_borrado_en     TIMESTAMPTZ
);

-- M:N SENSOR ↔ VARIABLE
CREATE TABLE IF NOT EXISTS tb_variables_soporta_sensores (
	vss_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vss_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
												ON UPDATE CASCADE ON DELETE CASCADE,
	vss_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
												ON UPDATE CASCADE ON DELETE RESTRICT,
	vss_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	vss_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	vss_modificado_en TIMESTAMPTZ,
	vss_borrado_en    TIMESTAMPTZ
);

-- UMBRALES
CREATE TABLE IF NOT EXISTS tb_umbrales (
	um_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	um_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	um_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	um_valor_min     DOUBLE PRECISION,
	um_valor_max     DOUBLE PRECISION,
	um_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	um_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	um_modificado_en TIMESTAMPTZ,
	um_borrado_en    TIMESTAMPTZ,
	CONSTRAINT uq_umbral UNIQUE (um_id_sensor, um_id_variable),
	CONSTRAINT ck_umbral_rango CHECK (
		(um_valor_min IS NULL OR um_valor_max IS NULL) OR (um_valor_min <= um_valor_max)
	),
	CONSTRAINT ck_umbral_not_both_null CHECK (
		(um_valor_min IS NOT NULL OR um_valor_max IS NOT NULL)
	)
);
CREATE INDEX IF NOT EXISTS idx_um_sensor_variable ON tb_umbrales(um_id_sensor, um_id_variable);

-- LECTURAS DE SENSORES
CREATE TABLE IF NOT EXISTS tb_lecturas_sensores (
	ls_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ls_valor         VARCHAR(255) NOT NULL,
	ls_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	ls_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	ls_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	ls_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ls_modificado_en TIMESTAMPTZ,
	ls_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_lecturas_sensor   ON tb_lecturas_sensores(ls_id_sensor);
CREATE INDEX IF NOT EXISTS idx_lecturas_variable ON tb_lecturas_sensores(ls_id_variable);
CREATE INDEX IF NOT EXISTS idx_lecturas_fecha    ON tb_lecturas_sensores(ls_creado_en);

-- ALERTAS
CREATE TABLE IF NOT EXISTS tb_alertas (
	a_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	a_mensaje       VARCHAR(250) NOT NULL,
	a_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
										 ON UPDATE CASCADE ON DELETE RESTRICT,
	a_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	a_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	a_modificado_en TIMESTAMPTZ,
	a_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alertas_sensor_fecha ON tb_alertas(a_id_sensor, a_creado_en);

-- ALERTAS POR USUARIO
CREATE TABLE IF NOT EXISTS tb_alertas_usuarios (
	au_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	au_id_alerta     INT NOT NULL REFERENCES tb_alertas(a_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	au_id_usuario    INT NOT NULL,
	au_leido         BOOLEAN NOT NULL DEFAULT FALSE,
	au_leido_en      TIMESTAMPTZ,
	au_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	au_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
	au_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	au_modificado_en TIMESTAMPTZ,
	au_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_au_usuario ON tb_alertas_usuarios(au_id_usuario);

-- ========================= --
-- CREACION DE PRIMERA BASE DE DATOS DE EMPRESA(Tech Solutions)
-- ========================= --

CREATE DATABASE iot_empresa_tech_solutions_db;

\c iot_empresa_tech_solutions_db;

-- =========================
--  EMPRESARIAL (TENANT)
-- =========================

-- PROYECTOS
CREATE TABLE IF NOT EXISTS tb_proyectos (
	p_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	p_nombre         VARCHAR(45) NOT NULL,
	p_descripcion    VARCHAR(250),
	p_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	p_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	p_modificado_en  TIMESTAMPTZ,
	p_borrado_en     TIMESTAMPTZ
);

-- NODOS
CREATE TABLE IF NOT EXISTS tb_nodos (
	n_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	n_nombre         VARCHAR(45) NOT NULL,
	n_ubicacion      VARCHAR(100),
	n_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	n_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	n_modificado_en  TIMESTAMPTZ,
	n_borrado_en     TIMESTAMPTZ,
	n_id_proyecto    INT NOT NULL REFERENCES tb_proyectos(p_id)
											ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nodos_proyecto ON tb_nodos(n_id_proyecto);

-- SENSORES
CREATE TABLE IF NOT EXISTS tb_sensores (
	s_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	s_nombre         VARCHAR(45) NOT NULL,
	s_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	s_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	s_modificado_en  TIMESTAMPTZ,
	s_borrado_en     TIMESTAMPTZ,
	s_id_nodo        INT NOT NULL REFERENCES tb_nodos(n_id)
											ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sensores_nodo ON tb_sensores(s_id_nodo);

-- VARIABLES (catálogo)
CREATE TABLE IF NOT EXISTS tb_variables (
	v_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	v_nombre         VARCHAR(100) NOT NULL,
	v_unidad         VARCHAR(15),
	v_descripcion    VARCHAR(250),
	v_var_json       VARCHAR(100) NOT NULL UNIQUE,
	v_estado         BOOLEAN NOT NULL DEFAULT TRUE,
	v_creado_en      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	v_modificado_en  TIMESTAMPTZ,
	v_borrado_en     TIMESTAMPTZ
);

-- M:N SENSOR ↔ VARIABLE
CREATE TABLE IF NOT EXISTS tb_variables_soporta_sensores (
	vss_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vss_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
												ON UPDATE CASCADE ON DELETE CASCADE,
	vss_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
												ON UPDATE CASCADE ON DELETE RESTRICT,
	vss_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	vss_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	vss_modificado_en TIMESTAMPTZ,
	vss_borrado_en    TIMESTAMPTZ
);

-- UMBRALES
CREATE TABLE IF NOT EXISTS tb_umbrales (
	um_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	um_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	um_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	um_valor_min     DOUBLE PRECISION,
	um_valor_max     DOUBLE PRECISION,
	um_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	um_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	um_modificado_en TIMESTAMPTZ,
	um_borrado_en    TIMESTAMPTZ,
	CONSTRAINT uq_umbral UNIQUE (um_id_sensor, um_id_variable),
	CONSTRAINT ck_umbral_rango CHECK (
		(um_valor_min IS NULL OR um_valor_max IS NULL) OR (um_valor_min <= um_valor_max)
	),
	CONSTRAINT ck_umbral_not_both_null CHECK (
		(um_valor_min IS NOT NULL OR um_valor_max IS NOT NULL)
	)
);
CREATE INDEX IF NOT EXISTS idx_um_sensor_variable ON tb_umbrales(um_id_sensor, um_id_variable);

-- LECTURAS DE SENSORES
CREATE TABLE IF NOT EXISTS tb_lecturas_sensores (
	ls_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ls_valor         VARCHAR(255) NOT NULL,
	ls_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	ls_id_variable   INT NOT NULL REFERENCES tb_variables(v_id)
											ON UPDATE CASCADE ON DELETE CASCADE,
	ls_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	ls_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ls_modificado_en TIMESTAMPTZ,
	ls_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_lecturas_sensor   ON tb_lecturas_sensores(ls_id_sensor);
CREATE INDEX IF NOT EXISTS idx_lecturas_variable ON tb_lecturas_sensores(ls_id_variable);
CREATE INDEX IF NOT EXISTS idx_lecturas_fecha    ON tb_lecturas_sensores(ls_creado_en);

-- ALERTAS
CREATE TABLE IF NOT EXISTS tb_alertas (
	a_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	a_mensaje       VARCHAR(250) NOT NULL,
	a_id_sensor     INT NOT NULL REFERENCES tb_sensores(s_id)
										 ON UPDATE CASCADE ON DELETE RESTRICT,
	a_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	a_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	a_modificado_en TIMESTAMPTZ,
	a_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alertas_sensor_fecha ON tb_alertas(a_id_sensor, a_creado_en);

-- ALERTAS POR USUARIO
CREATE TABLE IF NOT EXISTS tb_alertas_usuarios (
	au_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	au_id_alerta     INT NOT NULL REFERENCES tb_alertas(a_id)
											ON UPDATE CASCADE ON DELETE RESTRICT,
	au_id_usuario    INT NOT NULL,
	au_leido         BOOLEAN NOT NULL DEFAULT FALSE,
	au_leido_en      TIMESTAMPTZ,
	au_estado        BOOLEAN NOT NULL DEFAULT TRUE,
	au_borrado       BOOLEAN NOT NULL DEFAULT FALSE,
	au_creado_en     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	au_modificado_en TIMESTAMPTZ,
	au_borrado_en    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_au_usuario ON tb_alertas_usuarios(au_id_usuario);

-- Fin del script de inicialización.